#!/bin/bash

read -p "Enter an integer: " num

if (( (($num % 3)) == 0 )) && (( (($num % 5 == 0)))) 
then
	echo "FizzBuzz"
elif (( (($num % 5)) == 0 ))
then 
	echo "Buzz"
elif (( (($num % 3)) == 0 ))
then
	echo "Fizz"
else
	echo $num
fi
