#!/bin/bash

read -p "How old are you: " age

case $age in

[0-4])
	echo "too young for school"
	;;
5)
	echo "Kindergarten"
	;;
[6-9]|1[0-8])
	grade=$((age-5))
	echo "$grade"
	;;
*)
	echo "Too old for school"
	;;
esac
