#!/bin/bash


file="./file1"


if [ -f $file ];then
echo "file exists"
fi

cat $file | while read line
do
	echo $line | cut -f1,2,3 -d' ' >> file2
done

while read line
do
  echo $line
done < ./file2
